services:
  Users/hiroyukimiyazaki/talkn-ch-gateway/common/ch-configs:
    container_name: talkn-ch-gateway-Users/hiroyukimiyazaki/talkn-ch-gateway/common/ch-configs
    image: nginx:alpine
    volumes:
      - /Users/hiroyukimiyazaki/talkn-ch-gateway/common/ch-configs/Users/hiroyukimiyazaki/talkn-ch-gateway/common/ch-configsnginx.conf:/etc/nginx/nginx.conf
      - /Users/hiroyukimiyazaki/talkn-ch-gateway/common/ch-configs/Users/hiroyukimiyazaki/talkn-ch-gateway/common/ch-configsopenssl.crt:/etc/ssl/certs/openssl.crt
      - /Users/hiroyukimiyazaki/talkn-ch-gateway/common/ch-configs/Users/hiroyukimiyazaki/talkn-ch-gateway/common/ch-configsopenssl.key:/etc/ssl/certs/openssl.key
    ports:
      - "/a11/b22/:443"
    environment:
      - IS_DOCKER=true
      - NODE_ENV=development
    command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
    deploy:
      resources:
        limits:
          memory: 2g
    networks:
      - talkn-global

networks:
  talkn-global:
    external: true
